export interface AuditAnalysisResult {
  url: string;
  timestamp: string;
  score: number;
  summary: AuditSummary;
  pages: PageAnalysis[];
  sitemap: SitemapResult;
  robots: RobotsResult;
  content: ContentAnalysis;
  seo: SEOAnalysis;
  trust: TrustAnalysis;
  performance: PerformanceAnalysis;
}

export interface AuditSummary {
  totalIssues: number;
  criticalIssues: number;
  highIssues: number;
  mediumIssues: number;
  pagesScanned: number;
  approvalProbability: number;
}

export interface PageAnalysis {
  url: string;
  status: number;
  title: string | null;
  metaDescription: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogType: string | null;
  ogImage: string | null;
  canonical: string | null;
  jsonLd: string | null;
  schemaTypes: string[];
  wordCount: number;
  hasH1: boolean;
  headingStructure: string[];
  hasAuthor: boolean;
  hasDate: boolean;
  hasAutoGenerated: boolean;
  issues: Issue[];
}

export interface Issue {
  type: "critical" | "high" | "medium" | "low";
  category: string;
  message: string;
  detail: string;
  suggestion: string;
}

export interface SitemapResult {
  accessible: boolean;
  urlCount: number;
  urls: string[];
  issues: Issue[];
}

export interface RobotsResult {
  accessible: boolean;
  content: string;
  hasSitemap: boolean;
  issues: Issue[];
}

export interface ContentAnalysis {
  aiProbability: number;
  aiSignals: string[];
  fillerPhrases: string[];
  hasPersonalVoice: boolean;
  hasConcreteExamples: boolean;
  hasDataOrStats: boolean;
  articleCount: number;
  avgWordCount: number;
  issues: Issue[];
}

export interface SEOAnalysis {
  metaTagsScore: number;
  schemaScore: number;
  sitemapScore: number;
  internalLinks: number;
  issues: Issue[];
}

export interface TrustAnalysis {
  hasPrivacyPolicy: boolean;
  hasTermsOfService: boolean;
  hasContactPage: boolean;
  hasAboutPage: boolean;
  hasAuthorBios: boolean;
  hasSocialLinks: boolean;
  hasBusinessInfo: boolean;
  contactMethods: string[];
  issues: Issue[];
}

export interface PerformanceAnalysis {
  hasNextImage: boolean;
  hasExplicitDimensions: boolean;
  imageCount: number;
  scriptsSize: string;
  issues: Issue[];
}
